### ISSUE TITLE
Memory Usage?

### ISSUE THREAD

**Issue by dcomartin** [unitycontainer/container#86]
I'm trying to troubleshoot some memory issues.  When using dotMemory for a process that has been running for awhile, we noticed the `_registrations` of type `HashRegistry` holding on to a lot of memory.    When I dig into it further, it appears that `BuilderContext` has an `Existing` property from prior resolutions?  Which seems odd since the registrations in question are Transient.  Not sure why it would be hanging on to these references which I then assume are not getting disposed.

https://github.com/unitycontainer/container/blob/90c6f3ec5ff6173d8379f8081ae3967b2459c57d/src/Builder/BuilderContext.cs#L109

I could be way off and just trying to understand what's happening.  Any help pointing me in the right direction if I'm doing something wrong.  We didn't seem to notice any of this until we upgraded to 5.7.3 awhile ago.

**Comment by dcomartin** [comment]
I do see that this was added fairly recently.  I've forked and am troubleshooting myself so I can try and figure out what's happening.  Not exactly what other info to provide.

**Comment by ENikS** [comment]
Could you create a test case demonstrating the problem?

**Comment by dcomartin** [comment]
Ya I'm trying to work through creating a test(s) with dotMemory Unit to see if I can replicate what I'm experiencing.

**Comment by dcomartin** [comment]
Just for more info,  we upgrade to the latest and we are still noticing high memory usage.

I have tried to use dotMemory Unit to try and replicate in a test but cannot.  I'm still trying to dig through my latest dotMemory profile to try and figure out why container is holding so much memory.  As mentioned before the `_registrations` is what's really large.

Here's a couple screenshots of dotMemory results.

<img width="447" alt="capture" src="https://user-images.githubusercontent.com/1577098/39879472-e59c70d6-5448-11e8-9257-228e2ee68adc.PNG">

Here's an individual entry.

<img width="519" alt="capture2" src="https://user-images.githubusercontent.com/1577098/39879477-e7cb5ce6-5448-11e8-8b2a-4ae389679a75.PNG">

What's interesting here is the existing entry has a reference to `AdminQueryContext` which is registered as Transient.  Why is it hanging on to this reference?

**Comment by dcomartin** [comment]
Also the above is the top level instance of the container in the application, I believe.  I don't understand the unity internals enough however to know why this instance (parent) would have references when nothing is resolved from the root but rather is done from a child container.  If this is the case, this makes sense that these instances are being held on to because the parent container is never disposed.  So even if a child container is disposed, these objects will hang around because they are also associated to the parent, which is never disposed.

**Comment by ENikS** [comment]
The parent _registrations is holding all 'factories' for all known types unless it is overridden in child container. Next child will resolve from existing, already compiled pipeline in root factory and will not be require to rebuild the resolver. That behavior is by design.

As with everything in life you have to pay the price. Either compact and slow or large and fast. Unity is taking later approach. 

I think it could be optimized and made better. After 5.7.3 release memory footprint has increased but performance jumped tenfold. 

The numbers shown in your pics are rather high but it could be totally legit if these all registrations. I really need the test case to diagnose this issue. Perhaps small app I could run?

**Comment by ENikS** [comment]
``BuildContext`` should not be referenced beyond the resolution request. If it is held longer, it is a bug.

**Comment by dcomartin** [comment]
In the meantime, I'm downgrading to the 5.5.5 which is what we were using prior to 5.7.3.

**Comment by ENikS** [comment]
I am not seeing this behavior in my tests. Are you doing something special in your app?

**Comment by dcomartin** [comment]
Nothing special that I'm aware of. 

After we downgraded to 5.5.5, without any other changes, we are seeing a pretty drastic change in memory usage.

When running dotMemory since the downgrade and comparing snapshots, here's the difference.

5.5.5
<img width="365" alt="capture" src="https://user-images.githubusercontent.com/1577098/40010773-cad3c898-5773-11e8-9bab-0250ece49765.PNG">

5.8.6

<img width="387" alt="capture2" src="https://user-images.githubusercontent.com/1577098/40010852-00cdc200-5774-11e8-873d-d84073cdfc03.PNG">

**Comment by ENikS** [comment]
It's been 2 month. No test case has been provided so I am assuming this is no longer an issue.

**Comment by appel1** [comment]
If you have registered both a mapping from an interface to a class and just the class resolving the interface retains all resolved instances in the chain to that interface. Can we reopen this issue or do you prefer that I create a new one?

The following example will retain the instances of both Bar and Foo. 

```csharp
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            m_container.RegisterType<Foo>();
            m_container.RegisterType<IFoo, Foo>();

            m_container.Resolve<Bar>();
        }

        private readonly IUnityContainer m_container = new UnityContainer();
    }

    public interface IFoo
    {
    }

    public class Foo : IFoo
    {
    }

    public class Bar
    {
        public Bar(IFoo foo)
        {
        }
    }
```

**Comment by ENikS** [comment]
Fixed in ee085a2703d9313c3208e91a92bfb59b0e0d00c2

**Comment by prashanthmp7** [comment]
Hi,

I am facing the exact issue. We are using the latest version as of today that is 5.11.1. Looks like the issue still persists.
